// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var config, configurePhoton;
  configurePhoton = require('./photon');
  config = require('../config.json');
  configurePhoton('localhost:8090', config);
}.call(this);
