// Generated by CoffeeScript 2.0.0-beta7
module.exports.status = function (flag) {
  if (flag) {
    return 'YES';
  } else {
    return 'NO';
  }
};
module.exports.numericStatus = function (flag) {
  if (flag) {
    return '1';
  } else {
    return '0';
  }
};
