// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var action, args, config, description, host, options, password, Photon, photon;
  Photon = require('./photon');
  config = require('./config.json');
  options = {
    configure: 'Apply configuration to factory device.',
    reset: 'Reset device configuration to factory settings.',
    status: 'Get device connection status.',
    battery: 'Get device battery status.',
    attached: 'Get attached hosts.',
    reboot: 'Reboot device.',
    monitor: 'Monitor device configuration. Send useful events.'
  };
  args = process.argv.slice(2);
  action = args[0];
  password = args[1] || 'admin';
  host = args[2] || '192.168.1.1';
  if (!options[action]) {
    console.log('Options:');
    for (action in options) {
      description = options[action];
      console.log('  ' + action + ': ' + description);
    }
    return;
  }
  photon = new Photon(host, config);
  photon.authenticate(password, function () {
    return photon[action](args, function (err, results) {
      return console.log(results);
    });
  });
}.call(this);
