// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var password;
  password = function (passwd) {
    return {
      ac: 'ADMIN',
      act: 'act_change_passwd',
      passwd: passwd,
      confirm: passwd
    };
  };
  password.schema = {
    type: 'string',
    required: true
  };
  module.exports = password;
}.call(this);
