// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var async, attached, auth, battery, config, mainEndpoint, network, password, Photon, reboot, request, reset, router, schema, status, system, time, validate, wifi;
  async = require('async');
  request = require('request');
  validate = require('jsonschema').validate;
  schema = require('./schema').schema;
  config = require('../config.json');
  attached = require('./attached');
  auth = require('./auth');
  battery = require('./battery');
  network = require('./network');
  password = require('./password');
  reboot = require('./reboot');
  reset = require('./reset');
  router = require('./router');
  status = require('./status');
  system = require('./system');
  time = require('./time');
  wifi = require('./wifi');
  mainEndpoint = 'webmain.cgi';
  Photon = function () {
    function Photon(param$) {
      this.hostname = param$;
    }
    Photon.prototype.sendRequest = function (form, done) {
      var jar, timeout, uri;
      if (null == done)
        done = function () {
        };
      jar = true;
      timeout = 1e3;
      uri = 'http://' + this.hostname + '/cgi-bin/' + (form.endpoint || mainEndpoint);
      return request.post({
        form: form,
        jar: jar,
        timeout: timeout,
        uri: uri
      }, done);
    };
    Photon.prototype.handleResponse = function (done) {
      return function (error, response) {
        return done(error, JSON.parse(response.body).data);
      };
    };
    Photon.prototype.authenticate = function (password, done) {
      return this.sendRequest(auth(password), done);
    };
    Photon.prototype.configure = function () {
      var errors, requests;
      errors = validate(config, schema).errors;
      if (errors.length)
        throw new Error(['Configuration file error'].concat(errors.map(function (param$) {
          var cache$, message, property;
          {
            cache$ = param$;
            property = cache$.property;
            message = cache$.message;
          }
          return '' + property + ' ' + message;
        })).join('\n'));
      requests = {
        setupSystem: function (this$) {
          return function (done) {
            return this$.sendRequest(system(config.system), done);
          };
        }(this),
        setupTime: function (this$) {
          return function (done) {
            return this$.sendRequest(time(config.time), done);
          };
        }(this),
        setupWifi: function (this$) {
          return function (done) {
            return this$.sendRequest(wifi(config.wifi), done);
          };
        }(this),
        setupNetwork: function (this$) {
          return function (done) {
            return this$.sendRequest(network(config.network), done);
          };
        }(this),
        setupRouter: function (this$) {
          return function (done) {
            return this$.sendRequest(router(config.router), done);
          };
        }(this),
        setupPassword: function (this$) {
          return function (done) {
            return this$.sendRequest(password(config.password), done);
          };
        }(this)
      };
      return async.auto(requests);
    };
    Photon.prototype.status = function (done) {
      return this.sendRequest(status, this.handleResponse(done));
    };
    Photon.prototype.attached = function (done) {
      return this.sendRequest(attached, this.handleResponse(done));
    };
    Photon.prototype.battery = function (done) {
      return this.sendRequest(battery, this.handleResponse(done));
    };
    Photon.prototype.reset = function () {
      return this.sendRequest(reset);
    };
    Photon.prototype.reboot = function () {
      return this.sendRequest(reboot);
    };
    return Photon;
  }();
  module.exports = Photon;
}.call(this);
