// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var status, system;
  status = require('./flags').status;
  system = function (param$) {
    var disableWifiWhileUsb;
    disableWifiWhileUsb = param$.disableWifiWhileUsb;
    return {
      act: 'act_rndis_config',
      getset: 'set',
      use_wifi_off: status(disableWifiWhileUsb)
    };
  };
  system.schema = {
    disableWifiWhileUsb: {
      type: 'boolean',
      required: true
    }
  };
  module.exports = system;
}.call(this);
